USE [master]
GO

/****** Object:  Database [XmlStorage]    Script Date: 3/26/2018 6:56:06 AM ******/
CREATE DATABASE [XmlStorage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'xml_store', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\xml_store.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'xml_store_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\xml_store_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [XmlStorage] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XmlStorage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [XmlStorage] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [XmlStorage] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [XmlStorage] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [XmlStorage] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [XmlStorage] SET ARITHABORT OFF 
GO

ALTER DATABASE [XmlStorage] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [XmlStorage] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [XmlStorage] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [XmlStorage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [XmlStorage] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [XmlStorage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [XmlStorage] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [XmlStorage] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [XmlStorage] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [XmlStorage] SET  DISABLE_BROKER 
GO

ALTER DATABASE [XmlStorage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [XmlStorage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [XmlStorage] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [XmlStorage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [XmlStorage] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [XmlStorage] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [XmlStorage] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [XmlStorage] SET RECOVERY FULL 
GO

ALTER DATABASE [XmlStorage] SET  MULTI_USER 
GO

ALTER DATABASE [XmlStorage] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [XmlStorage] SET DB_CHAINING OFF 
GO

ALTER DATABASE [XmlStorage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [XmlStorage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [XmlStorage] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [XmlStorage] SET QUERY_STORE = OFF
GO

USE [XmlStorage]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [XmlStorage] SET  READ_WRITE 
GO

USE [XmlStorage]
GO

/****** Object:  Table [dbo].[XmlObject]    Script Date: 3/26/2018 6:56:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XmlObject](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [nvarchar](max) NULL,
	[FileVersion] [nvarchar](max) NULL,
	[DateTime] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.XmlObject] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

